export const CATEGORY_LABELS: Record<string, string> = {
  bed_bath_table: "Cama, Mesa y Baño",
  health_beauty: "Salud y Belleza",
  sports_leisure: "Deportes y Ocio",
  furniture_decor: "Muebles y Decoración",
  housewares: "Utensilios Domésticos",
  watches_gifts: "Relojes y Regalos",
  telephony: "Telefonía",
  garden_tools: "Jardín y Herramientas",
  auto: "Automotriz",
  toys: "Juguetes",
  cool_stuff: "Novedades",
  perfumery: "Perfumería",
  computers: "Computadoras",
  informatica_accessories: "Informática y Accesorios",
  office_furniture: "Muebles de Oficina",
  stationery: "Papelería",
  electronics: "Electrónicos",
  audio: "Audio",
  cds_dvds_musicals: "CDs, DVDs y Música",
  music: "Música",
  dvds_blu_ray: "DVDs y Blu-ray",
  fixed_telephony: "Telefonía Fija",
  tablets_printing_image: "Tablets e Impresión",
  computers_accessories: "Accesorios de Computadora",
  pc_gamer: "PC Gamer",
  books_general_interest: "Libros",
  books_imported: "Libros Importados",
  christmas_supplies: "Suministros Navideños",
  agro_industry_and_commerce: "Agroindustria",
  construction_tools: "Herramientas de Construcción",
  construction_tools_afety: "Seguridad en Construcción",
  flowers: "Flores",
  food_drink: "Alimentos y Bebidas",
  food: "Alimentos",
  drinks: "Bebidas",
  home_comfort: "Confort del Hogar",
  home_appliances: "Electrodomésticos",
  home_appliances_2: "Electrodomésticos 2",
  home_confort: "Confort del Hogar",
  industry_commerce_and_business: "Industria y Comercio",
  air_conditioning: "Aire Acondicionado",
  fashion_childrens_clothes: "Ropa Infantil",
  fashion_shoes: "Calzado",
  fashion_sport: "Ropa Deportiva",
  fashion_underwear_beach: "Ropa Interior y Playa",
  fashion_male_clothing: "Ropa Masculina",
  fashion_bags_accessories: "Bolsos y Accesorios",
  fashion_female_clothing: "Ropa Femenina",
  fashion: "Moda",
  small_appliances: "Pequeños Electrodomésticos",
  small_appliances_home_oven_and_coffee: "Electrodomésticos de Cocina",
  security_and_services: "Seguridad y Servicios",
  baby: "Bebé",
  books_technical: "Libros Técnicos",
  cine_photo: "Cámaras y Fotografía",
  market_place: "Market Place",
  party_supplies: "Suministros para Fiestas",
  beach_toy: "Juguetes de Playa",
  costruction_tools: "Herramientas de Construcción",
  drivers: "Conductores",
  fashion_handbags: "Bolsos",
  grooming: "Cuidado Personal",
  hygiene: "Higiene",
  kitchen: "Cocina",
  la_cuisine: "Cocina",
  luggage_accessories: "Maletas y Accesorios",
  musical_instruments: "Instrumentos Musicales",
  office: "Oficina",
  other: "Otros",
  padaria: "Panadería",
  portateis: "Portátiles",
  portable: "Portátiles",
  home_appliance: "Electrodomésticos",
};
