export const STATE_OPTIONS = [
  { value: "AC", label: "Acre" },
  { value: "AL", label: "Alagoas" },
  { value: "AP", label: "Amapá" },
  { value: "AM", label: "Amazonas" },
  { value: "BA", label: "Bahia" },
  { value: "CE", label: "Ceará" },
  { value: "DF", label: "Distrito Federal" },
  { value: "ES", label: "Espírito Santo" },
  { value: "GO", label: "Goiás" },
  { value: "MA", label: "Maranhão" },
  { value: "MT", label: "Mato Grosso" },
  { value: "MS", label: "Mato Grosso do Sul" },
  { value: "MG", label: "Minas Gerais" },
  { value: "PA", label: "Pará" },
  { value: "PB", label: "Paraíba" },
  { value: "PR", label: "Paraná" },
  { value: "PE", label: "Pernambuco" },
  { value: "PI", label: "Piauí" },
  { value: "RJ", label: "Rio de Janeiro" },
  { value: "RN", label: "Rio Grande do Norte" },
  { value: "RS", label: "Rio Grande do Sul" },
  { value: "RO", label: "Rondônia" },
  { value: "RR", label: "Roraima" },
  { value: "SC", label: "Santa Catarina" },
  { value: "SP", label: "São Paulo" },
  { value: "SE", label: "Sergipe" },
  { value: "TO", label: "Tocantins" },
];

export const ORDER_STATUS_OPTIONS = [
  { value: "delivered", label: "Entregado" },
  { value: "shipped", label: "Enviado" },
  { value: "processing", label: "Procesando" },
  { value: "canceled", label: "Cancelado" },
  { value: "invoiced", label: "Facturado" },
  { value: "unavailable", label: "No disponible" },
  { value: "approved", label: "Aprobado" },
  { value: "created", label: "Creado" },
];

export const CATEGORY_OPTIONS = [
  { value: "bed_bath_table", label: "Cama, Mesa e Baño" },
  { value: "health_beauty", label: "Salud y Belleza" },
  { value: "sports_leisure", label: "Deportes y Ocio" },
  { value: "furniture_decor", label: "Muebles y Decoración" },
  { value: "housewares", label: "Utensilios Domésticos" },
  { value: "informatica_accessories", label: "Informática y Accesorios" },
  { value: "watches_gifts", label: "Relojes y Regalos" },
  { value: "telephony", label: "Telefonía" },
  { value: "garden_tools", label: "Jardín y Herramientas" },
  { value: "auto", label: "Automotriz" },
];
